version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rag_network

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    networks:
      - rag_network

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Console Port
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    networks:
      - rag_network

  fastapi_app:
    build: ./fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    networks:
      - rag_network

  # --- Airflow Services ---
  airflow-init:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    env_file:
      - .env
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init && \
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com && \
        airflow connections add 'minio_conn' --conn-type 's3' --conn-login '${MINIO_ROOT_USER}' --conn-password '${MINIO_ROOT_PASSWORD}' --conn-host 'minio' --conn-port 9000 --conn-extra '{"aws_session_token": null, "host": "http://minio:9000"}'
    networks:
      - rag_network
    depends_on:
      - postgres

  airflow-webserver:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    command: webserver
    networks:
      - rag_network
    depends_on:
      - airflow-init

  airflow-scheduler:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    command: scheduler
    networks:
      - rag_network
    depends_on:
      - airflow-init

volumes:
  postgres_data:
  minio_data:
# docker-compose.yml (Add this service definition)

streamlit_app:
    build:
      context: . # Assumes your Dockerfile for Streamlit is in the project root
      dockerfile: Dockerfile.streamlit # We'll create this file next
    ports:
      - "8501:8501" # Expose Streamlit's default port
    environment:
      # Point to the FastAPI service name.
      # If running locally outside docker-compose, you might need to change this to http://localhost:8000
      FASTAPI_URL: http://fastapi_app:8000
      # You might also need to pass other environment variables needed by your app,
      # like OpenAI API keys if not handled solely by the FastAPI backend.
      # However, for this setup, FastAPI handles the OpenAI calls.
    volumes:
      - ./app:/app # Mount the directory containing app.py for easy development
    depends_on:
      - fastapi_app
      - redis
      - postgresql
      - chromadb # Add other services if your Streamlit app directly needs them, though typically it only needs FastAPI
    networks:
      - mynetwork # Ensure it's on the same network as FastAPI

  # ... other services ...

networks:
  mynetwork:
    driver: bridge
